---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: meetly
spec:
  encryptedData:
    .dockerconfigjson: AgCVUSuPQSzg+OJtMKyL6HRiTVcAhN0u24qt56a6HYBPKlQGFHbcdzj/UloVtCsWNbRAW4+daQRgWLA5YmtFC3jj0W+oKKUGPQmMfq34Zzx6pH2XPjJsxyz8T4rPtDnRs842zWcF1nGhfUWjbIHh4Md3PDoEkqxzieFSektywC9dBWsbG0wciDGDj13f5ILR8yKes3m6nvDdMnKq7G1pGTSaeE3L9ME726qwDGJFfMT0SZgtLvzFaojyLGqL/YZMuLviuDrWo7wwiwtehT//sAjS8dwudZuRrhA2tz7ZwjWxsdQ+XxPQSEJFyfzXRupg9WPgmIp+5D8Cwl1fsh5MBkmZ6eabpmzRwMzyzo9ceOJBsOG6zYIattB/PYmFE2JNCQZuiPnphe8jReo//bg75TN/B6lnYLgYM+jHYf0PunfRfatlHHvcvirNNpavAZHXqHxxc8C1gacoqkcdBGA6x1OwEP7A/sF7Bqu9dhgffQ/K7xboYLGSJ6v0EihLTl6XtxJXX7zZmK+OOQBzuKbgW06MRi4734DWy8mHjOdq1SyYwnRPY+XnLZflHg5ptBKiMrx9guMRXBfsnjUNJyy0jN/plb2+D8sTOIX9Th1ZDk+isE+FJa6paK+B7ynllpbe5bl84ZbBPeLSt44dfy5SdA4VQXi8rOhAKx5LoLCEw9Mim1WhL6E55KoXPiVTu2CSyhVMmNBsvY9QcBfc9RVNyFZlGLJ/hrLkCwLmWQtD473L1HIZfsfLJKMR3/wjMjtY1hYNn1Orgb66ZQuVsy13MSJsjuU9q/vkb99Gx7hYEtcw5Ic+EgdQ2dbS6HGLOTg0Tqs034h5Deo8JxxgdxqJ29pDI4/zk5tOpqK4EgAwcaO+cm4S8kNd7oMn0czUU+ZlDdMsXWnVy3qZNyM5TYgwxibpjf4OcXFGPRYB2K7gZLPEL9Lbteg/OkhlLTbAd+1iBg==
  template:
    metadata:
      name: ghcr-pull
      namespace: meetly
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meetly-jwt
  namespace: meetly
spec:
  encryptedData:
    JWT_SECRET: AgAKEnBJXJ6fxhsN4Jt7tEmBzni67J/43k9aTtOguCTUF8eupuLNA/hi3ZxiPFQQN7t505pVYKUArdeLhGGSBh09NsWOxo0vku90rgLR4G8wTE1k0/CMi8ERR72i+IT4KXyiCD/3Kn4guNgFVyLkvPXByCrqWFz1uqaMzbROzEp0JV6WNu0g/R5jpANr+bPCiWWnXKe3JskD3kKZUBXSjlxaIj3DQaG/UQbYhRrdJvXi/rUhk5xQem5NeF0JNKu2skG0XZenUeF32eFz2Ol8Eq6d9rWtpEZlN+oE2UuRxFTu8ds/ag0NFC2i2YeH1sPH2r3wsC5TQTTqd85gXzJeGs0Gj+fKmDOHUFm1JfKZLH8HbdyWm76Z8Y+eWxNYH4h8EnR8Jmj6Dw/A97t2iaQOWP2La7ywqUcpxkF36P5gZZRLus5Mp789egFMQuMhWPjGDCWFoUxWe/DbMC7SyhEAFqNtX7ciafaU7DFwtgnhjMR5x1l8Ixaa0bHs9qbZ3T54z0C4KGwddEwyGIPGVG1HKsoxaQFca37bWGlcoic1Ssp4I3AWU7ZfcQFuF31Ni7JfTPDeBm9jF/zxKmrybslF2OgvjFba+CwksDu+T8JHpO7hygD9k8+0cWX0W4NFtmbqE+PEVE6OhelO6qdB+cQ/fnyKqp9hVFY0NPOLgPzIw+ndwY5JfH8uMUu63OeXYMgSyq27tVVU2xzAjk8hmhuRoxZrSDXrTJdZYnwSUun2Aa2ALuScuzOyglAk8kue1DUhiL8dfvJUA3eJl56EnFJDLoaW
  template:
    metadata:
      name: meetly-jwt
      namespace: meetly
