access: public

components:
  - name: meetly-backend
    image:
      repository: ghcr.io/mescoczubinski/meetly-backend
      tag: v0.0.1
    port: 8080
    paths:
      - /api
    probe:
      path: /api/health
    env:
      - name: PORT
        value: "8080"
      - name: CORS_ORIGIN
        value: https://meetly.czubinski.dev
    secretEnv:
      JWT_SECRET: meetly-jwt
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
  - name: meetly-frontend
    image:
      repository: ghcr.io/mescoczubinski/meetly-frontend
      tag: v0.0.1
    port: 3000
    paths:
      - /
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 300m
        memory: 128Mi
