---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: ghcr-pull
  namespace: homepage
spec:
  encryptedData:
    .dockerconfigjson: AgA4IaUrSa7+/jXH4wQ12Dq1r4GD/0fuGfGL1IJBnWb/rnbDZZ4DTKK4niXgQscpIB8D365vxMVaOCHbXRISE+6isJC4plpKVGCjuxq+W1NcIPDsZdOYg+r8gOU825hhWUkfFG2fO4NTEbjTxOE97mNo5onjLPCH4nzzB3kk34pdakVqZbdS2ypl/K24uoJ/xqjwEzspwog0vDiBEfWgJS+Sf26SjIUp8Uedy7mFryiHQqnnZ3YzMPCsijWCqKxyIUq/5349lfdS5nzOMLM+qhIqGhBD6XZYRN8GlLZ9P9TvpZ5mnxjPfQ8QO0NLm8lVxnp3yRcyXGVzRkVaaohPil+JuryDYK95Ts/hEjMI1lwXSMPPv0/qkXC709SJ/03+1U7hYA8mYMCn0kvoWlyC8hQLfuPsiQAt0CyjoolACIfraH6g/eD/GW3UtZWitjldUIpVpAWYx2LfSbgqwBsv2vvSOQ42TSEVzNtP1DNAxuhZu8W2Q4nJT33uAXy5NsFhr5o6QlOkQBirl8Ybem5SY/k2Me2hE76J+IVCtCpspwwDlOUJJTTG7x9ziQypV+7HUNNO+BTBvezSZKItHtPOQIkHTEk/9R44Q4PNPLaqO4EDSNEXzJLX4c28Wt27jaJGD+6vf5Xl/BW1xW+uDBHkT0raBbAarOzwg/76aYkgEmQUe4OtQhNBNHbbXSrNBO/Gb68Un9hgWewQ3/+SOcjp1jSoZLAa6Ki7kFsAhuDOXEOH9imNOxoP2N1qKyGeDTNMCESN1HKt7nyJPqSBpcP6rWiMtWB/3Ev4QP/gjWOJ4yvM+xwcWl6UbcQVdTpDZr4FdAUO9FN/vm8xoDfEu8GN9mti9itiRMDtJfdoPH5gFbX1eFYpqgQ4GvFlFg+FtI19zzlkYH5w8Yvhyt8nbKyeAEkq9d9QHBAp9oSafPpR8v7ZzajH2HI/StT5l6GOGZVqhA==
  template:
    metadata:
      name: ghcr-pull
      namespace: homepage
    type: kubernetes.io/dockerconfigjson
