imagePullSecrets:
  - ghcr-pull

components:
  - name: homepage
    image:
      repository: ghcr.io/mescoczubinski/homepage
      tag: v0.0.1
    port: 80
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 200m
        memory: 64Mi

ingress:
  host: czubinski.dev
  entrypoint: public
  paths:
    - path: /
      service: homepage
      port: 80
