host: czubinski.dev
access: public

components:
  - name: homepage
    image:
      repository: ghcr.io/mescoczubinski/homepage
      tag: v0.0.1
    port: 80
    paths:
      - /
    probe:
      path: /
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 200m
        memory: 64Mi
