apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MescoCzubinski/homelab.git
    targetRevision: main
    path: .
    directory:
      recurse: true
      include: "{apps/beszel/*,apps/convertx/*,apps/samba/*,apps/stirling/*,apps/syncthing/*,infra/*/application.yaml,infra/cloudflared/*,infra/middleware/*}"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
