---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-password
  namespace: samba
spec:
  encryptedData:
    password: AgC03bN+VlmCCBltZpydLUZoH4qJiPhKbvslCrgC+6zwCd3WxA9GPNom2Q9GL4SMHdh55TUmL3tMohFu0hdne72BUCe4ZMw+Z4ViUaeFjxUFNHut2rG3c9S54bX1W9ZEQCYECg+gZ6yhtqOaSrvJMUlcWNevIu7L+IgxaTOxpVUdMGB6BZjqMJ66it79mHeLLb12Zh9PylxD4bbGIrPizlETKuPPdFvYPM0kfkGXiIhUxCjLS/yfc0m7i0+HbxNbM7fn0jk3lO0t7rHY+tsjb3jbzfMp5evo37sf/Xsd2f9qZpGTij7PuOSXi1gTCSum7O2HTlKlUMLXMv33gAzRCMbniePJb6ABSFzndFc12KElyglgEeE/JAvkisL4Z6T4BalErXZ+F8E2zCj4tG39tLhzsP13K8m//otI59X16FjGYZLrWJpf0iWxX3aGg4uXmMSCEJc1K5Vnte/+z967mV7wp4jLVKG6dEaoDboJRuV+7GevLVOY1W5nXH1YqrRjTKLCbwVJ97fpvRQX+MElsDcV5ehfZfUEOh/zrTF2jcjQeokk1eQ7BewQtfgbYsZMdX4JMTVZYToXCzBfBNp5RZHY6nq6Vy9GCv56jrS3kTbUKBLbgcKCmvqriWa3M4Q+Cx6oFtteX/2IPnng9kb27KgpoetdxYdsR72tPhSAII28Z/Lg+LTO2pqfV0lLXiXKPyL7XrZ84ivHkdYMOUKizmVYZzFfbQ==
  template:
    metadata:
      name: samba-password
      namespace: samba
