service:
  spec:
    type: NodePort
    externalTrafficPolicy: Local

ports:
  web:
    nodePort: 30001
  websecure:
    nodePort: 30002
  syncthing-tcp:
    port: 22000
    expose:
      default: true
    exposedPort: 22000
    protocol: TCP
    nodePort: 30022
  samba-tcp:
    port: 445
    expose:
      default: true
    exposedPort: 445
    protocol: TCP
    nodePort: 30445
