---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: syncthing-password
  namespace: syncthing
spec:
  encryptedData:
    password: AgA/gH8KLZ81Ly05qWlADqEqEJ+rr6QP39tPzN9/Mu8AqQd6KwRu+5y5kscwB2/f6PgEeC5djhmXm7jglle14BS5gHNUWuX/GpQz9oOA6NJDigOMEK51J318j8X6SR0Vdu44sWCQcB8q3oXrN1oYfDp8P6+y/7iwO26+F/SngsWqMgS2wIoW5sULIQrBcpW0NRaNcqwplGgxELBucsf5HVABiJPV5t7Ddq2pQ5qXkh6aihhDT02xgNt252x6k7Cg1yI9FxX42uZR3Wr1o944Ah0DdpvVpks4XZnkmGI8Ot6urHSLgPSHLtbOWuh0KeF/Z8qcx3vZ4nbeVofqlUQMC/+ZYHS8K8FKDg/1i33C2bVrZtKSVHe539g80bLR3xyPwX7gQKqs5rYpZYySgA83zE/UdAy2DTo++cBOH+AlUTJJUmGqttF56dLC+9IkO0PvqOfwlHRwo4etxBscQQ3LiJd2mxMphGw6O/RqtnUV0Qk2N2Acyc3gQ1TUSzCP1YQ3HtA0gsiuL4Z3pCtudgEwRCRsm5h+Zl9I5MxhboWgkaugMqOQRfd+ON+F5RM7RZWOa+2/bgSDLDvatFRLA9W7/iEUBvxbcTdiuhDVauWqBR+aItic1pD6U25viFcPBxECRjdwvn8t8q88zDetYZa5U17gOAqEYVht/hlGCgTDAVOktwyao5SZkidBF6hz+lI/yBb23AUIV+S5WuHQvIaiziJOAQEQJQ==
    username: AgBnIJU4YjKoyNR/2iCmWh7MUmsF6DjgxCo5eT35aOl3bIQWr3PDyMHcelQapPKYFWIpu1sqilx1J3etPyYE84KwzbSPMQW6hNsXCjuLA8uZdMm/+Jds5k1TU/Mi2ex5pvJabo5TlMXNpOMahWUGW6DhhzlZyBag/ahOx7DTQkEkTRL4DJiIYl0DH39ITUG+tAMR7RJZmNimlQ6gfp0jTa8PPEBJBeTkD5m2PFTcp0s3MsKnDeLB4Ldh09F6QI3H87+am7YTzHQOLmEUVQY70j1+0piBpnE4L7NKvjo1ySe8Ii0YZ2Rg/gnGz/86wr5cNIK8g9KZAXC26PUtcYpJY88T6iVkotYHrkIo7VR+TSIs0nNMVEEd/z7HRyHNq3gwUNsLDl2HxuKPgOBhDnn4i68j3mr4aOA5FLeWo5wSV7f4QG2UoWwdgg/FzYXQRDnM5crjPFmn/QZet9SSrGB3+UIIHF89qE9u5ZNvh8sVg6PPMpQ/EFtHYWkAyHwVJCDUQ9DbSYikpKun2EyGjTLyEPRf/FJbs7vKwmKFXE7nRMDLM/j02ANyHpfQFkl23BKqzk7CaUhcZr8IrlwdUb9wa3qzi1YzdAomaDAo1kf7j936kWn55tPAuFnf8ayLVk+Ki35Lp4BSpkuT84Xu+Ad67zDTzNSRNs6kO0IlvWsvV5igidZ9joStEWZhyzz6YJh+M407zWMolg==
  template:
    metadata:
      name: syncthing-password
      namespace: syncthing
