apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-public
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: public
spec:
  ingressClassName: traefik
  rules:
    - host: whoami.czubinski.dev
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: whoami
                port:
                  number: 80
