---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-key
  namespace: beszel
spec:
  encryptedData:
    key: AgCLX1d9gJUqmWiZ1bYn7iqBVdUo0MI4JswxW8BqBCTMm9i53idtBOBLMAWNOuF19+UhweCOFHMBdIpEhHoxGEhu19amgaCpHBev4wYmF/mNrKpLwguW//85+xoaEmtpyXKPlDrXi02ctcV3fS6E+9ksQAlvOtL9wBi0XTPmGJbp9Rx/fmEVRq7LWWARoo2R/w0gYOxkrxgFsCwlvWnT2kCUnhMLYdnCxGXPvOzdW0YHdc6aJZJTlK8hQugTfQ6o64pbZprtgIFjUBEaDrzPSKM31siI5pQTCKCmYhTLGCTmJj8e/gqXXDLwx3rwcRtYsAkLifkYGKW1bO5UcIZzPm2Fls9WW8FrKOnZCf8djJOJHlmNJTbYqE+SEHmnsRGtRoAwTCEDP7+4sVx/o8QsSYtw23KgYwM69Lc7hJk2CWN49cEDfuG6sSiw+w1R5hsYDJ0Ubhbh4XKMJ8UC9ppMAZAgNY/SC5cNB8C74uQllIxmm5LH95VF5gndm122xk2sZf2DOW9KLWqZmR4KBIl48bM/+wRx/Ch7QeO5297j9D7T8QRQVkKZ/g8pyzIXjjbA0wSecG84KRT8e7iTm3CwWuLjWVYp/kNO3SiSmbCi9Dpfm3nTokRmGyIGN4XdNaBFjZmDEM6tnXSgQBnp6qTQz8FXy21fsplCWzQ0sgFO2UWk6fupmR3wGVbNiX1dY95vLVvNpWDv9hWo0WRaM0nLKglZT/d3TkOAcGAS7l0aS1xukhk4U/N+oVnZ5gz4z2dDr8mBXPB1PtY4p1hiAOy45fPpwKzzodRijBp3q+46D6qksw==
  template:
    metadata:
      name: beszel-key
      namespace: beszel
