---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: cloudflare-dns-token
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgC0G6dnJuiHgm7MaxFJ7RFadLNFc4RT/LXtSqrsBunhVnCD2JXKedS4UJF14USuPs8uMrdPHAydlHTZO8kBU66+xWsRAjdaxCKuI18gogBLMSs+F6OWImUVTV/GS9mNq5R+5gt2iS4TxEl8OLtl9LRuMkX9SNVwOrJ9MhdOjd/0V5stgrhWL53MMB/tGjgRqmFDW4ma7r90dTQi30zA1moWNXJlNfNHc9YHjCkZymeuBQXS44toMx+t9YmJQmpJv+cbGXneywHv0NdG8+ttY6ViuUVBOBP0cqMVQmt7ogdUQ7kTYN5GK3Dmw4qRanzmXXm5HqueyTR+/2Yeu+1xeEGObmS0O406PYqVgjF/emQG9sPu0uhrPKdoaNomtiGrf2Jgp39DJIrHz3XcP5mu0t75f0CK9OjakLojJYin3BrLnBgKHKpp8IyelqvLUDDdp8yB1esVpix0mAEvQ6S/PZvXC/QAkh3FW3Z7/nIn9v4x+77wEQy2AYVWVznRfYSvTYRE2EIb5BGTVVKl0+7jhlXUyk0mxBx6LiqefOk24oUtGvJiU//cXMOwvlDHoYfSed0iPZLDrE0pG/JdLd7EPKfNErG7PVJWePWTpdnuQ0ObXLLhFnYPX86WBJFOW58vMsILpQfvOj4/wYWoQPDNKqrmrvqicp762Yx/cAAf34LNLHf85KNjQfUkK5nfshzbioPt/m8+Gx4l+5h3V8giAeveAeFKGEpZeA6mvKrbBVugMPTuqURlpmRfwIi2W6U4mP6dfH80DQ==
  template:
    metadata:
      name: cloudflare-dns-token
      namespace: traefik
