service:
  enabled: true
  type: ClusterIP

ports:
  web:
    port: 8000
    hostPort: 80
  websecure:
    port: 8443
    hostPort: 443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: czubinski.dev
            sans:
              - "*.czubinski.dev"
  public:
    port: 9000
    expose:
      default: false
  syncthing-tcp:
    port: 22000
    hostPort: 22000
    protocol: TCP
  samba-tcp:
    port: 445
    hostPort: 445
    protocol: TCP

certificatesResolvers:
  letsencrypt:
    acme:
      email: REMOVED
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-token
        key: CF_DNS_API_TOKEN

persistence:
  enabled: true
  existingClaim: traefik-acme
  path: /data

deployment:
  initContainers:
    - name: acme-permissions
      image: busybox:1.37
      command:
        - sh
        - -c
        - touch /data/acme.json && chown 65532:65532 /data/acme.json && chmod 600 /data/acme.json
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: data
          mountPath: /data
