service:
  enabled: true
  spec:
    type: ClusterIP

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesIngress:
    publishedService:
      enabled: false
    ingressEndpoint:
      ip: 192.168.1.100

ports:
  web: null
  websecure:
    port: 443
    hostPort: 443
    hostIP: 192.168.0.1
    asDefault: true
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: czubinski.dev
            sans:
              - "*.czubinski.dev"
  public:
    port: 8001
    exposedPort: 8080
    forwardedHeaders:
      trustedIPs:
        - 10.244.0.0/16
    expose:
      default: true
  samba-tcp:
    port: 445
    hostPort: 445
    hostIP: 192.168.0.1
    protocol: TCP
  syncthing-tcp:
    port: 22000
    hostPort: 22000
    hostIP: 192.168.0.1
    protocol: TCP

additionalArguments:
  - --entryPoints.websecure.address=:443/tcp
  - --entryPoints.samba-tcp.address=:445/tcp
  - --entryPoints.syncthing-tcp.address=:22000/tcp

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-token
        key: CF_DNS_API_TOKEN

persistence:
  enabled: true
  existingClaim: traefik-acme
  path: /data

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

deployment:
  initContainers:
    - name: acme-permissions
      image: busybox:1.37
      command:
        - sh
        - -c
        - touch /data/acme.json && chown 65532:65532 /data/acme.json && chmod 600 /data/acme.json
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: data
          mountPath: /data
