apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/server/traefik/acme
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: traefik-acme
  resources:
    requests:
      storage: 128Mi
