apiVersion: v1
data:
  config.xml: |
    <configuration version="52">
        <folder id="Notes" label="Notes" path="/var/syncthing/data/Notes" type="sendreceive">
            <device id="5SWC46N-Z3JIGQ2-3U2XH77-KOCOUW3-UJ674QT-THR555H-UAN2DVG-H6XU4AO"/>
            <device id="IFW3ZPK-FGBR63F-ZEKRKF3-EHZA2YU-65M2N2V-KXLSI5P-E4OHPNW-675ABAP"/>
            <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG"/>
        </folder>
        <folder id="Pictures" label="Pictures" path="/var/syncthing/data/Pictures" type="sendreceive">
            <device id="5SWC46N-Z3JIGQ2-3U2XH77-KOCOUW3-UJ674QT-THR555H-UAN2DVG-H6XU4AO"/>
            <device id="IFW3ZPK-FGBR63F-ZEKRKF3-EHZA2YU-65M2N2V-KXLSI5P-E4OHPNW-675ABAP"/>
        </folder>
        <folder id="Shared" label="Shared" path="/var/syncthing/data/Shared" type="sendreceive">
            <device id="5SWC46N-Z3JIGQ2-3U2XH77-KOCOUW3-UJ674QT-THR555H-UAN2DVG-H6XU4AO"/>
            <device id="IFW3ZPK-FGBR63F-ZEKRKF3-EHZA2YU-65M2N2V-KXLSI5P-E4OHPNW-675ABAP"/>
            <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG"/>
        </folder>
        <folder id="Memes" label="Memes" path="/var/syncthing/data/Memes" type="sendreceive">
            <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG"/>
        </folder>
        <folder id="ReactionMemes" label="ReactionMemes" path="/var/syncthing/data/ReactionMemes" type="sendreceive">
            <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG"/>
        </folder>
        <folder id="Phone" label="Phone" path="/var/syncthing/data/Phone" type="sendreceive">
            <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG"/>
        </folder>

        <device id="5SWC46N-Z3JIGQ2-3U2XH77-KOCOUW3-UJ674QT-THR555H-UAN2DVG-H6XU4AO" name="myLaptop">
            <address>dynamic</address>
        </device>
        <device id="IFW3ZPK-FGBR63F-ZEKRKF3-EHZA2YU-65M2N2V-KXLSI5P-E4OHPNW-675ABAP" name="myDesktop">
            <address>dynamic</address>
        </device>
        <device id="J22COXJ-OIFALUG-ZQEJIHV-RALME62-QRPFDTW-GW35ZBK-W23T3L4-LUJSJAG" name="myPhone">
            <address>dynamic</address>
        </device>

        <gui enabled="true" tls="false">
            <address>0.0.0.0:8384</address>
        </gui>

        <options>
            <listenAddress>tcp://0.0.0.0:22000</listenAddress>
            <globalAnnounceEnabled>false</globalAnnounceEnabled>
            <relaysEnabled>false</relaysEnabled>
        </options>
    </configuration>
kind: ConfigMap
metadata:
  name: syncthing-config
