apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.9.2
      helm:
        releaseName: argocd
        valueFiles:
          - $values/infra/argocd/values.yaml
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: infra/argocd
      directory:
        recurse: true
        include: "{ingress-*.yaml,applications/*}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
