apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: convertx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MescoCzubinski/homelab.git
    targetRevision: main
    path: tools/convertx
  destination:
    server: https://kubernetes.default.svc
    namespace: convertx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
