apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: charts/app
      helm:
        releaseName: homepage
        valueFiles:
          - $values/apps/homepage/values.yaml
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: apps/homepage
      directory:
        include: "{namespace.yaml,sealed-secret.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
