apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 1.*
      helm:
        releaseName: argocd-image-updater
        valueFiles:
          - $values/infra/argocd-image-updater/values.yaml
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: infra/argocd-image-updater
      directory:
        include: "{image-updaters.yaml,sealed-secret.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
