apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meetly
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: charts/app
      helm:
        releaseName: meetly
        valueFiles:
          - $values/apps/meetly/values.yaml
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: apps/meetly
      directory:
        include: "sealed-secret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: meetly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
