apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MescoCzubinski/homelab.git
    targetRevision: main
    path: tools
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
