apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 41.6.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/infra/traefik/values.yaml
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:MescoCzubinski/homelab.git
      targetRevision: main
      path: infra/traefik
      directory:
        include: "{namespace.yaml,volume-acme.yaml,sealed-secret.yaml,middleware-*.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
