---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBTDqIthAvmV5N/YKJlHFI806nTzNDJRB5pLjz+M04okaXIaGzYFcumuhjAInqtmb9NL63AEuFP0Kfu9Dq6ynenqW8CjVXI/8XJOQiY/1G4lk60RzG/YhVq79ncHfjkcVDEMNr6H9k3ysmN5wbF5GUFSn9xO3MArhBxd0/sjJL2syJhoch3cLpgN443ABEaKeB22iFqngpcw6p5naXiphckYt0ewynK3ktMZRy89A6yhJaQXELL7osewnhTtoX6sZo7DolpOkYQRjzTxCLwGqas81cbJJ111hxJW+UsUB4IbT37v9N4BYBERtRcD23o1IJJvNB4a/a0u2O8jmZDyGxA6h/3OubgivhzEjSYoLtj7kUuizc0zi/PmIXhalJUiDy5P+dGi1dpjLGbR5v13G0ZTx54zIlHGmKhKoVChaYr1frLP7xm7/glIKJvNf47qfRjQv5RJ3Y/CamJmXiBFJisFKFZ5yiwZfoMxYFLdUElsdcS2NUeOdEddVxJzvw/YHE/bgpwL/2j9/oSl6/QB2nuyKfRZQqKCqlHcG+97QxccwiZr4THFuwGyNT/OqtluigeGPMQ7Wp85RVo3Fb1I5PiPTiHAwgXyegTBGxNMWjrN7f4Qv3UFJa1RHaXXfJfXT/ijDOM9FqzmeHuyyECi6r5RyTVxJvyW1v0KYCPdvH9x69OqgzRyd6N4YyOBCv7SPwZaSgVjncA7JVWkBF6Ek4lOPey55Mk7BIDsfvFGwFxJ7TlaYZH4HHIIV/IG80MUMCUXoQYEUVAGqCvgCyMU4y3tjCT7ldhTZQFOiSEODizyT/+UGNsflIPM4dpp1JuomsGl1ItSndB5QBDlac9pShzG+9qUXSyuwDPSyRwQ32PMtszFfN5hy1qIzHGCgpWZWJWopUhrjYYg78ncmfO8v3dFbrLXNxAbCNz0SCiFgx05Mxopmaq4/VMdg==
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
