---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgDX3WVRI8/miUypfP6IdPKL9QHUJqcSMXkvrkqAVdD5xNeONrIrbSqR/xMgvvdq9ejBY3CDB1aju+8Z3Ct076eGkYsp63Uv7UsnBo06Wbqjd013gcdzENAAZk3Gn2HpHi/O+47qBpxjgKJO/IWSuLqTizrwh7wMq+2hv3YNBXjVb+IAu06pNzPn8caJj7wIKh26yWb/l2S0bCnGyXUJ+wQ7ysDRiqgMd354XvCkR3cOqyk8tNvi+nERDgWwMeN8cnNNr/CAHKRhFY46tx7IzJNDl/tA/qCFkoU9toJWX42SUrF8yHeTXIoQcdbn8QUxSbJ+VRrHF0RLo5FOL/9Hx6GOfvcR7PBj49vKgZMkT/+cfxE07j4rFzvxdAehUFoxbEKSMDXZgcvyX27DXCUIvsojpYY+ioAVg287oV82LU6H4VcMBiLSgiB2J2W2yG/+KE215DKjDqhoAPB8jcjcUffBKuAtnNuqwgKMf5Jvj31TtbPf6bl3GAVXxDAJAl9QiIRR7AhaTyG9ZsWGdsEAViWeTpOo6EfEH8NOZXiK0DmTJBz4BGypcZHuM/n3x9eLgpJZQ3DzZ3cFLF55/smOuwzI1dgG8E8D19q4lWFnDlzBypJqF4RA0dsS7ackaQISMOyu3IGqzkdGSh4sS+lVLW0MREVuffHkfyzLo/7gN74FjqXXLox7qZ5co3E9/uQntiHoP88Tyn4PbepUiDdIHmQtJsvuSwqylxBR434NNEVAQSgEgxo03qxFW+a7stKjkkGvaZVQ9pnGB9y36pYXFhItzcO/8z3q9Vl+tKlZCWM0MFbHqzAS4wwfRRh8nrIpcRW7xgdPCXyu4iSFa68uhxc18+mmdF1osTfLAzYsYHbqdoNgRendTXxGbszaTd7FzGF3KFr05P3cI9edAsPMkOtaFWDvb/FSQ8AEg6hxlAA8keP8RCUZGpeSdNO4bgBMhA==
  template:
    metadata:
      name: ghcr-pull
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
