---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-webhook
  namespace: argocd
spec:
  encryptedData:
    github: AgC97BIp0UvS5tuREXlg3vpBDkQ7QSwU9lDACn9oxOEeGTOwU5fm4TRdNpDPjSdzowxrUrfcM09zuAr+Gt098NC9GhdQJ8wxBHnML+du7yd2xo+R4lFbRP9taQq53JKcmx9rMYrNz62QPG5eVuvYzSjrgqNmucmZa8T6FerZWM/qKjyGxrNpPLSwlNMfjPTmpLB2Ye+LpwXs7JIu6TNtbeMWu1c7bx2M+xDCNsMLg96Oimk6jWnPQ1IWbd5U8J3T6Z8BEGosqtpn/1DzV0N0UYh/H416lXf6/5aUFc4fV5o1EXRvwF9gzYrhZI0c2R8TCtIbpmF5D0ADhcWPmhtKvB0w7D2fQK5QOMTYqA9bT41oojECnpjKinqYU65jc5w6pIyCabHGS2QiCnNsx4p1mZToAlfuCdg/9yMKs4/k1bWur9kpqUtRv8R6Tnbm8jVok5bX5BHmnJPxYd1Hi4R847NrSt7eVvjTk4fn4kQ0wzSQYHUWlUKBV4fYHjV6SAyhvhisHzkjRvnpX4ZEw3dIt9Citdif7xC4S3gmoffjzTvDiojvGOUl1edRYPfngohGMg0PnkMzOKikBQUkn0ehCv8hRa22ZrYAhKpic8RIskuP3TM5KMvas/b79Z8YjF3yOhXaP6AEd66V8vRHMSx3y+HO0cC7O/eep9Z5s8S4I2gFF7005+oPtAwW141qdWDn0pyINmXSUN3H2gl98VzRph1QEeo+ipuDiqTb4tR3lrn1nX12+uzsDVCpAOQ+cHmR+vWEv+BTGp0Js3ntBMo1SjvJ
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-webhook
      namespace: argocd
