global:
  domain: argocd.czubinski.dev

configs:
  params:
    server.insecure: true
  secret:
    githubSecret: "$argocd-webhook:github"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-http-vpn-only@kubernetescrd

dex:
  enabled: false

notifications:
  enabled: false
